### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch when null value is chained

### ISSUE THREAD

**Issue by aeberhart** [dashjoin/jsonata-java#28]
This works:

    jsonata("$toMillis(aaa)").evaluate(null);

Written like this, we get the exception:

    jsonata("aaa ~> $toMillis()").evaluate(null);

```
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Functions.call(Functions.java:2158)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata$JFunction.call(Jsonata.java:2217)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.applyInner(Jsonata.java:1746)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.apply(Jsonata.java:1678)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.evaluateFunction(Jsonata.java:1648)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.evaluateApplyExpression(Jsonata.java:1524)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata._evaluate(Jsonata.java:202)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.evaluate(Jsonata.java:131)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.evaluate(Jsonata.java:2589)
	at com.dashjoin.jsonata/com.dashjoin.jsonata.Jsonata.evaluate(Jsonata.java:2550)
```

**Comment by uw4** [comment]
This is an edge case "null vs undefined". The evaluation is the same as this:
https://try.jsonata.org/UzUPqu9aK
